### ISSUE TITLE
4.19

### ISSUE THREAD

**Issue by lagauche** [monsieurgustav/UE4-OSC#56]
Sorry if this is the wrong place to ask, but has anyone tested with 4.19 yet? : )

**Comment by monsieurgustav** [comment]
I tried it during preview IIRC, and it worked.

Generally, it takes no (or little) update to the plugin to work on the new version. You should just try!

**Comment by matewfeel** [comment]
I just tried building the plugin on 4.19.2, unfortunately the automatic build failed : ''Project could not be compiled, try build from source manually''
....

i then also tried to generate new solution files to try and build manually but no luck: 

Running E:/Program Files (x86)/Epic Games/UE_4.19/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="D:/Projects/UnrealEngine/VI_Spout_Kinect/VI_Spout_Kinect.uproject" -game -rocket -progress
Discovering modules, targets and source code for project...
While compiling D:\Projects\UnrealEngine\VI_Spout_Kinect\Intermediate\Build\BuildRules\VI_Spout_KinectModuleRules.dll:
ERROR: d:\Projects\UnrealEngine\VI_Spout_Kinect\Plugins\UE4-OSC-master\OSC\Source\OSC\OSC.Build.cs(3,15) : error CS0101: The namespace 'UnrealBuildTool.Rules' already contains a definition for 'OSC'
ERROR: UnrealBuildTool Exception: Unable to compile source files.

'''''''


How can i get this to work ?

thanks

**Comment by monsieurgustav** [comment]
Hi,
The plugin works in 4.19.

It looks like you have several modules (project, plugins) named "OSC", is that possible?
Possibly in the engine and in the project ?

**Comment by matewfeel** [comment]
I just checked in the root folder of the 4.19 engine, no OCS plugin to be found there, i also tried and search for it in the root dir and a bunch of files came up, but not sure if any of those are related to the issue https://ibb.co/gfsUny
