### ISSUE TITLE
Cannot build for 4.7.2

### ISSUE THREAD

**Issue by th3m4ri0** [monsieurgustav/UE4-OSC#4]
Hi,
When I trying adding the plugin to a 4.7.2 project, I get this error on compilation : 
![capture d ecran 2015-03-12 a 14 52 31](https://cloud.githubusercontent.com/assets/2685884/6625596/74199f52-c8c7-11e4-8c38-41451ab23898.png)

**Comment by monsieurgustav** [comment]
Hi,
The plugin builds and works fine on 4.7.2.
Remember you must create a C++ project (or "Add Code" to an existing blueprint project) in order to compile plugins.
If the error persists, please post a complete error log.

**Comment by monsieurgustav** [comment]
MacOSX or Windows, by the way ?

**Comment by th3m4ri0** [comment]
MacOSX. Didn't take the time to look into it.

**Comment by monsieurgustav** [comment]
Ok.
I have some reports about compile errors in MacOSX, on the last commit.
I'll look into it soon...

In the mean time, you can use the penultimate commit, which works fine on OSX.
https://github.com/monsieurgustav/UE4-OSC/tree/bde87ae9dcf1d18800ae33d40cdd03c40e96665b

**Comment by pop-eye** [comment]
Hey monsieurgustav I have been following the Unreal thread and checking and following the Github releases and notes, I am trying to compile the plugin and am getting the below errors. OS X 10.9.5  Xcode 6.1 Unreal 4.7.2. The penultimate release linked above is giving me the same errors. Thanks for your work on this, I am extremely excited to get the plugin running and aware you're looking in to it.

/Users/Shared/UnrealEngine/4.7/Engine/Source/Runtime/Core/Public/Templates/UnrealTypeTraits.h:203:17: error: incomplete type 'OscReceiverInputKey' used in type trait expression

/Users/Shared/UnrealEngine/4.7/Engine/Source/Runtime/Core/Public/Templates/UnrealTypeTraits.h:444:35: error: no type named 'ConstPointerType' in 'TCallTraits<OscReceiverInputKey>'

/Users/Shared/UnrealEngine/4.7/Engine/Source/Runtime/Core/Public/Templates/UnrealTypeTraits.h:449:33: error: incomplete type 'OscReceiverInputKey' used in type trait expression

/Users/Shared/UnrealEngine/4.7/Engine/Source/Runtime/Core/Public/Templates/UnrealTypeTraits.h:450:32: error: incomplete type 'OscReceiverInputKey' used in type trait expression

/Users/Shared/UnrealEngine/4.7/Engine/Source/Runtime/Core/Public/Templates/UnrealTypeTraits.h:459:28: error: incomplete type 'OscReceiverInputKey' used in type trait expression

/Users/Shared/UnrealEngine/4.7/Engine/Source/Runtime/Core/Public/Containers/Array.h:578:3: error: no matching function for call to 'DestructItems'

**Comment by monsieurgustav** [comment]
The latest commit should fix the issue.
