### ISSUE TITLE
UE4 4.21.0 Plugin Update?

### ISSUE THREAD

**Issue by markmccllm** [monsieurgustav/UE4-OSC#64]
Hello monsieurgustav,

Any chance their is an update planned for 4.21.0? I've been working with the plugin in 4.18 to 4.20, but no longer able to build using the latest release.

1>------ Skipped Build: Project: UE4, Configuration: BuiltWithUnrealBuildTool Win32 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: OSCTester, Configuration: Development_Editor x64 ------
2>Building 4 actions with 8 processes...
2>  [1/4] Module.OSC.gen.cpp
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/Receive/OscDispatcher.h(19): error C2061: syntax error: identifier 'FIPv4Address'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/Receive/OscDispatcher.h(41): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/Receive/OscDispatcher.h(41): error C2143: syntax error: missing ',' before '&'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/Receive/OscDispatcher.h(49): error C2039: 'pair': is not a member of 'std'
2>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\INCLUDE\new(16): note: see declaration of 'std'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/Receive/OscDispatcher.h(49): error C2143: syntax error: missing ';' before '<'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/Receive/OscDispatcher.h(49): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/Receive/OscDispatcher.h(49): error C2238: unexpected token(s) preceding ';'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/Receive/OscDispatcher.h(52): error C2143: syntax error: missing ';' before '<'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/Receive/OscDispatcher.h(52): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/Receive/OscDispatcher.h(52): error C2039: 'tuple': is not a member of 'std'
2>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\INCLUDE\new(16): note: see declaration of 'std'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/Receive/OscDispatcher.h(52): error C2238: unexpected token(s) preceding ';'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/OscSettings.h(83): error C2061: syntax error: identifier 'FIPv4Address'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/OscSettings.h(90): error C2065: 'FInternetAddr': undeclared identifier
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/OscSettings.h(90): error C2923: 'TSharedRef': 'FInternetAddr' is not a valid template type argument for parameter 'ObjectType'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/OscSettings.h(90): error C3203: 'TSharedRef': unspecialized class template can't be used as a template argument for template parameter 'InElementType', expected a real type
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/OscSettings.h(92): error C2039: 'unique_ptr': is not a member of 'std'
2>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\INCLUDE\utility(436): note: see declaration of 'std'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/OscSettings.h(92): error C2065: 'unique_ptr': undeclared identifier
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/OscSettings.h(92): error C2275: 'OscReceiverInputKey': illegal use of this type as an expression
2>  E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC\Private\Receive\OscReceiverInputKey.h(9): note: see declaration of 'OscReceiverInputKey'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/OscSettings.h(92): error C2974: 'TArray': invalid template argument for 'InElementType', type expected
2>  C:\Program Files\Epic Games\UE_4.21\Engine\Source\Runtime\Core\Public\Containers/Array.h(278): note: see declaration of 'TArray'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/OscSettings.h(92): error C2059: syntax error: '>'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC/Private/OscSettings.h(92): error C2238: unexpected token(s) preceding ';'
2>  [2/4] Module.OSC.cpp
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC\Private\Common\oscpack\osc\OscOutboundPacketStream.cpp(359): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\string.h(132): note: see declaration of 'strcpy'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC\Private\Common\oscpack\osc\OscOutboundPacketStream.cpp(637): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\string.h(132): note: see declaration of 'strcpy'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC\Private\Common\oscpack\osc\OscOutboundPacketStream.cpp(660): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\string.h(132): note: see declaration of 'strcpy'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC\Private\Receive\OscReceiverInputKey.cpp(13): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\stdio.h(1772): note: see declaration of 'sprintf'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC\Public\Common\OscFunctionLibrary.cpp(180): error C2660: 'FName::GetPlainANSIString': function does not take 0 arguments
2>  C:\Program Files\Epic Games\UE_4.21\Engine\Source\Runtime\Core\Public\UObject/NameTypes.h(639): note: see declaration of 'FName::GetPlainANSIString'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC\Public\Common\OscFunctionLibrary.cpp(192): error C2660: 'FName::GetPlainANSIString': function does not take 0 arguments
2>  C:\Program Files\Epic Games\UE_4.21\Engine\Source\Runtime\Core\Public\UObject/NameTypes.h(639): note: see declaration of 'FName::GetPlainANSIString'
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC\Public\Common\OscFunctionLibrary.cpp(192): error C2512: 'osc::BeginMessage': no appropriate default constructor available
2>  E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC\Public\Common\OscFunctionLibrary.cpp(192): note: No constructor could take the source type, or constructor overload resolution was ambiguous
2>E:\UNREAL\OSCTester\Plugins\OSC\Source\OSC\Public\Common\OscFunctionLibrary.cpp(214): error C2660: 'FName::GetPlainANSIString': function does not take 0 arguments
2>  C:\Program Files\Epic Games\UE_4.21\Engine\Source\Runtime\Core\Public\UObject/NameTypes.h(639): note: see declaration of 'FName::GetPlainANSIString'
2>UnrealBuildTool : error : UBT ERROR: Failed to produce item: E:\UNREAL\OSCTester\Plugins\OSC\Binaries\Win64\UE4Editor-OSC.dll
2>                        (see ../Programs/UnrealBuildTool/Log.txt for full exception trace)
2>Total build time: 10.63 seconds (Parallel executor: 0.00 seconds)
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3075: The command ""C:\Program Files\Epic Games\UE_4.21\Engine\Build\BatchFiles\Build.bat" OSCTesterEditor Win64 Development "E:\UNREAL\OSCTester\OSCTester.uproject" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
2>Done building project "OSCTester.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 1 skipped ==========

**Comment by monsieurgustav** [comment]
Hi,
I've just pushed a fix with the help of Josh Kerekes for 4.21.
(but it seems it won't fix you build errors...)

**Comment by monsieurgustav** [comment]
OK, I pushed a new build fix, you should be good to go now!

**Comment by markmccllm** [comment]
Hey monsieurgustav,
I can confirm the plugin is now successfully compiling in a fresh 4.21.0 project. Thank you so much for the quick response+fix, and for making this plugin available to the public. It's brought a lot of projects to life!

**Comment by monsieurgustav** [comment]
Thanks for the kind words! :)
