### ISSUE TITLE
Unable to build plugin with 4.17.2

### ISSUE THREAD

**Issue by michela** [monsieurgustav/UE4-OSC#49]
```
Running D:/Program Files/Epic Games/UE_4.17/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="C:/Users/michela/Downloads/UE4-OSC-master/UE4-OSC-master/Examples/OscDemo/OscDemo.uproject" -game -rocket -progress
Discovering modules, targets and source code for project...
Messages while compiling C:\Users\michela\Downloads\UE4-OSC-master\UE4-OSC-master\Examples\OscDemo\Intermediate\Build\BuildRules\OscDemoModuleRules.dll:
c:\Users\michela\Downloads\UE4-OSC-master\UE4-OSC-master\Examples\OscDemo\Source\OscDemo\OscDemo.Build.cs(7,9) : warning CS0618: 'UnrealBuildTool.ModuleRules.ModuleRules()' is obsolete: 'Please change your module constructor to take a ReadOnlyTargetRules parameter, and pass it to the base class constructor (eg. "MyModuleRules(ReadOnlyTargetRules Target) : base(Target)").'
c:\Users\michela\Downloads\UE4-OSC-master\UE4-OSC-master\Examples\OscDemo\Plugins\OSC\Source\OSC\OSC.Build.cs(5,10) : warning CS0618: 'UnrealBuildTool.ModuleRules.ModuleRules()' is obsolete: 'Please change your module constructor to take a ReadOnlyTargetRules parameter, and pass it to the base class constructor (eg. "MyModuleRules(ReadOnlyTargetRules Target) : base(Target)").'
c:\Users\michela\Downloads\UE4-OSC-master\UE4-OSC-master\Examples\OscDemo\Plugins\OSC\Source\OSC\OSC.Build.cs(41,53) : error CS0117: 'UnrealBuildTool.TargetRules' does not contain a definition for 'IsEditorType'
c:\Users\michela\Downloads\UE4-OSC-master\UE4-OSC-master\Examples\OscDemo\Source\OscDemo.Target.cs(8,9) : warning CS0618: 'UnrealBuildTool.TargetRules.TargetRules()' is obsolete: 'Please pass the TargetInfo parameter to the base class constructor (eg. "MyTargetRules(TargetInfo Target) : base(Target)").'
c:\Users\michela\Downloads\UE4-OSC-master\UE4-OSC-master\Examples\OscDemo\Source\OscDemoEditor.Target.cs(8,9) : warning CS0618: 'UnrealBuildTool.TargetRules.TargetRules()' is obsolete: 'Please pass the TargetInfo parameter to the base class constructor (eg. "MyTargetRules(TargetInfo Target) : base(Target)").'
UnrealBuildTool Exception: ERROR: UnrealBuildTool encountered an error while compiling source files

```

**Comment by Kaizien** [comment]
Having the same issue with both 4.17.1 and 4.17.2

**Comment by monsieurgustav** [comment]
Did you take the latest commits on "master", including "fix 4.17" ?
I fixed the build on 4.17, and IIRC it was working on 4.17.1.

**Comment by michela** [comment]
Yes confirming pulled master branch beyond that - commit 3c8a3d0127db18b9ef2b345dff343530115dd34b  

Double click on OscDemo.uproject
Msg: <dll built for another version, rebuild?>
Msg: OscDemo could not be compiled. Try rebuilding from source manually

**Comment by Kaizien** [comment]
can confirm as well,  not working on build 4.17

**Comment by monsieurgustav** [comment]
Oh, OK.
I've been lazy: the demo was out of date.
It is updated now.
